# Generated by Django 2.1.3 on 2018-11-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='post-image')),
                ('nomeEvento', models.CharField(max_length=200)),
                ('dataEvento', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Evento',
            },
        ),
    ]
