# Generated by Django 2.0.9 on 2018-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181126_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='static/imagens/parceiros')),
            ],
            options={
                'verbose_name': 'Parceiro',
            },
        ),
    ]
