# Generated by Django 2.0.9 on 2018-12-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='nome',
            field=models.CharField(default='Nome do Parceiro', max_length=200),
        ),
    ]
