# Generated by Django 2.0.9 on 2018-12-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parceiro_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parceiro',
            old_name='imagem',
            new_name='imagemParceiro',
        ),
    ]
