# Generated by Django 2.1.3 on 2018-12-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181214_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasjuniores',
            name='descricaoEmpresa',
            field=models.TextField(max_length=250),
        ),
    ]
