# Generated by Django 2.1.3 on 2018-12-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181214_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresasjuniores',
            options={'verbose_name': 'Empresa Junior', 'verbose_name_plural': 'Empresas Juniores'},
        ),
    ]
