# Generated by Django 2.1.3 on 2018-12-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181214_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasjuniores',
            name='logoEmpresa',
            field=models.ImageField(blank=True, upload_to='empresasJuniores/'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='logoEmpresa',
            field=models.ImageField(blank=True, upload_to='parceiros/'),
        ),
    ]
