# Generated by Django 2.1.3 on 2018-12-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181218_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasjuniores',
            name='logoEmpresa',
            field=models.ImageField(blank=True, upload_to='media/empresasJuniores'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='logoEmpresa',
            field=models.ImageField(blank=True, upload_to='media/parceiros'),
        ),
    ]
