# Generated by Django 2.1.3 on 2018-12-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181218_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasjuniores',
            name='logoEmpresa',
            field=models.ImageField(blank=True, upload_to='empresasJuniores'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='eventos'),
        ),
    ]
