# Generated by Django 2.1.3 on 2019-01-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181218_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='dataEvento',
        ),
        migrations.AlterField(
            model_name='empresasjuniores',
            name='logoEmpresa',
            field=models.ImageField(upload_to='empresasJuniores'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='logoEmpresa',
            field=models.ImageField(upload_to='parceiros'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='url',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
    ]
