# Generated by Django 2.1.3 on 2019-01-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190112_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='dataEvento',
            field=models.DateField(default='2019-01-01'),
            preserve_default=False,
        ),
    ]
