# Generated by Django 2.1.3 on 2019-02-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_mvv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mvv',
            options={'verbose_name': 'Missão, Visão, Valores', 'verbose_name_plural': 'Missão, Visão, Valores'},
        ),
        migrations.AlterField(
            model_name='mvv',
            name='valor_4',
            field=models.CharField(blank=True, max_length=40, verbose_name='Valor(opcional)'),
        ),
    ]
