# Generated by Django 2.1.3 on 2019-02-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190205_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='NossoTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosso_time', models.TextField(default='', max_length=374, verbose_name='Texto Nosso Time(max 374 caracteres)')),
            ],
            options={
                'verbose_name': 'Texto Nosso Time',
                'verbose_name_plural': 'Texto Nosso Time',
            },
        ),
    ]
