# Generated by Django 2.1.3 on 2019-02-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_nossotime'),
    ]

    operations = [
        migrations.AddField(
            model_name='nossotime',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='time', verbose_name='Imagem do Time'),
        ),
    ]
