# Generated by Django 2.1.3 on 2019-02-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_nossotime_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nossotime',
            old_name='imagem',
            new_name='imagemTime',
        ),
    ]
