# Generated by Django 2.1.3 on 2019-02-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190205_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nossotime',
            options={'verbose_name': 'Nosso Time', 'verbose_name_plural': 'Nosso Time'},
        ),
    ]
